In [ ]:
#Install lazypredict
pip install lazypredict

In [4]:
#Import Lazypredict and import all libraries
import lazypredict
from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split
import os
import pandas as pd
pd.set_option('float_format', '{:f}'.format)
import numpy as np

In [5]:
#Function to download and read delivery data CSV file
DATA_FILES_PATH = r"C:\\Users\\gchandr4\\Documents\\Blogs\\LazyPredict Classifier"
def load_customer_data(data_path=DATA_FILES_PATH):
    csv_path = os.path.join(data_path, "delivery_days_classifier.csv")
    return pd.read_csv(csv_path)

In [6]:
#load the data
data = load_customer_data()

In [7]:
#Print Data
data.head()

,Sold To,Ship To,Material,Price/Qty (USD),Qty,Total Price (USD),customer_req_date,new_delivery_date,no_of_delivery_days,on_or_before_delivered,target_ouput
0,1019733606,2020999825,40321040322,676,96,64896,3/4/2021,3/2/2021,-2,yes,0
1,1018240245,2011020734,40329968668,412,92,37904,3/3/2021,2/28/2021,-3,yes,0
2,1013606125,2021012587,40325529556,533,41,21853,3/4/2021,3/2/2021,-2,yes,0
3,1026160794,2018327772,40326638721,188,19,3572,3/3/2021,3/2/2021,-1,yes,0
4,1019775063,2012844064,40324755545,720,60,43200,3/5/2021,3/8/2021,3,no,1

In [8]:
#Split data into X and y target
X = data[['Sold To', 'Ship To', 'Material', 'Price/Qty (USD)', 'Qty', 'Total Price (USD)', 'no_of_delivery_days']]
y = data[['target_ouput']]

In [9]:
X

,Sold To,Ship To,Material,Price/Qty (USD),Qty,Total Price (USD),no_of_delivery_days
0,1019733606,2020999825,40321040322,676,96,64896,-2
1,1018240245,2011020734,40329968668,412,92,37904,-3
2,1013606125,2021012587,40325529556,533,41,21853,-2
3,1026160794,2018327772,40326638721,188,19,3572,-1
4,1019775063,2012844064,40324755545,720,60,43200,3
...,...,...,...,...,...,...,...
995,1024198808,2013483399,40323287609,629,2,1258,0
996,1022778913,2020047987,40326461044,646,53,34238,-2
997,1027798296,2028408862,40329208788,1414,5,7070,-1
998,1019461942,2020800690,40323276622,1211,97,117467,5
999,1018353320,2019115927,40321518085,1166,78,90948,-1

In [10]:
y

     target_ouput
0               0
1               0
2               0
3               0
4               1
..            ...
995             0
996             0
997             0
998             1
999             0

[1000 rows x 1 columns]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=.5,random_state =123)

In [13]:
clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

100%|██████████████████████████████████████████████████████████████████████████████████| 29/29 [00:00<00:00, 36.24it/s]

In [14]:
print(models)

                               Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model
AdaBoostClassifier             1.000000           1.000000 1.000000  1.000000
LinearDiscriminantAnalysis     1.000000           1.000000 1.000000  1.000000
XGBClassifier                  1.000000           1.000000 1.000000  1.000000
SGDClassifier                  1.000000           1.000000 1.000000  1.000000
RidgeClassifierCV              1.000000           1.000000 1.000000  1.000000
RidgeClassifier                1.000000           1.000000 1.000000  1.000000
RandomForestClassifier         1.000000           1.000000 1.000000  1.000000
Perceptron                     1.000000           1.000000 1.000000  1.000000
PassiveAggressiveClassifier    1.000000           1.000000 1.000000  1.000000
NearestCentroid                1.000000           1.000000 1.000000  1.000000
LogisticRegression             1.000000           1.000000 1.000000  1.000000
BaggingClassifier              1.000000           1.000000 1.000000  1.000000
LinearSVC                      1.000000           1.000000 1.000000  1.000000
GaussianNB                     1.000000           1.000000 1.000000  1.000000
ExtraTreesClassifier           1.000000           1.000000 1.000000  1.000000
DecisionTreeClassifier         1.000000           1.000000 1.000000  1.000000
CalibratedClassifierCV         1.000000           1.000000 1.000000  1.000000
BernoulliNB                    1.000000           1.000000 1.000000  1.000000
LGBMClassifier                 1.000000           1.000000 1.000000  1.000000
SVC                            0.998000           0.997642 0.997642  0.997999
QuadraticDiscriminantAnalysis  0.992000           0.990566 0.990566  0.991989
NuSVC                          0.984000           0.981132 0.981132  0.983956
KNeighborsClassifier           0.978000           0.974679 0.974679  0.977931
ExtraTreeClassifier            0.960000           0.961544 0.961544  0.960089
LabelSpreading                 0.960000           0.957187 0.957187  0.959919
LabelPropagation               0.960000           0.957187 0.957187  0.959919
DummyClassifier                0.508000           0.494497 0.494497  0.507005

                               Time Taken
Model
AdaBoostClassifier               0.021941
LinearDiscriminantAnalysis       0.000000
XGBClassifier                    0.029637
SGDClassifier                    0.012965
RidgeClassifierCV                0.015958
RidgeClassifier                  0.017968
RandomForestClassifier           0.147104
Perceptron                       0.000000
PassiveAggressiveClassifier      0.015622
NearestCentroid                  0.011968
LogisticRegression               0.026497
BaggingClassifier                0.039891
LinearSVC                        0.015622
GaussianNB                       0.015621
ExtraTreesClassifier             0.136031
DecisionTreeClassifier           0.017724
CalibratedClassifierCV           0.023703
BernoulliNB                      0.012965
LGBMClassifier                   0.053272
SVC                              0.008027
QuadraticDiscriminantAnalysis    0.017415
NuSVC                            0.014008
KNeighborsClassifier             0.044704
ExtraTreeClassifier              0.012965
LabelSpreading                   0.031243
LabelPropagation                 0.014095
DummyClassifier                  0.011968